// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKnowledgeEntry(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddKnowledgeEntry'](arg1, arg2, arg3, arg4);
}

export function ClearCommandLogs() {
  return window['go']['main']['App']['ClearCommandLogs']();
}

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteExpectRule(arg1, arg2) {
  return window['go']['main']['App']['DeleteExpectRule'](arg1, arg2);
}

export function DeleteKnowledgeEntry(arg1) {
  return window['go']['main']['App']['DeleteKnowledgeEntry'](arg1);
}

export function DeleteMacro(arg1) {
  return window['go']['main']['App']['DeleteMacro'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteSessionGroup(arg1) {
  return window['go']['main']['App']['DeleteSessionGroup'](arg1);
}

export function DeleteTunnelConfig(arg1) {
  return window['go']['main']['App']['DeleteTunnelConfig'](arg1);
}

export function ExecuteMacro(arg1, arg2) {
  return window['go']['main']['App']['ExecuteMacro'](arg1, arg2);
}

export function ExportKnowledgeBase() {
  return window['go']['main']['App']['ExportKnowledgeBase']();
}

export function GetAllKnowledgeEntries() {
  return window['go']['main']['App']['GetAllKnowledgeEntries']();
}

export function GetAllMacros() {
  return window['go']['main']['App']['GetAllMacros']();
}

export function GetAllSessionGroups() {
  return window['go']['main']['App']['GetAllSessionGroups']();
}

export function GetAllSessions() {
  return window['go']['main']['App']['GetAllSessions']();
}

export function GetAllTunnels() {
  return window['go']['main']['App']['GetAllTunnels']();
}

export function GetCommandLogs(arg1, arg2) {
  return window['go']['main']['App']['GetCommandLogs'](arg1, arg2);
}

export function GetExpectRules(arg1) {
  return window['go']['main']['App']['GetExpectRules'](arg1);
}

export function GetSerialPorts() {
  return window['go']['main']['App']['GetSerialPorts']();
}

export function GetSessionConfig(arg1) {
  return window['go']['main']['App']['GetSessionConfig'](arg1);
}

export function GetTFTPStatus() {
  return window['go']['main']['App']['GetTFTPStatus']();
}

export function ImportKnowledgeBase() {
  return window['go']['main']['App']['ImportKnowledgeBase']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function OpenSaveDialog(arg1) {
  return window['go']['main']['App']['OpenSaveDialog'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SFTPChmod(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPChmod'](arg1, arg2, arg3);
}

export function SFTPDelete(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPDelete'](arg1, arg2, arg3);
}

export function SFTPDownload(arg1, arg2) {
  return window['go']['main']['App']['SFTPDownload'](arg1, arg2);
}

export function SFTPDownloadDir(arg1, arg2) {
  return window['go']['main']['App']['SFTPDownloadDir'](arg1, arg2);
}

export function SFTPListDirectory(arg1, arg2) {
  return window['go']['main']['App']['SFTPListDirectory'](arg1, arg2);
}

export function SFTPMkdir(arg1, arg2) {
  return window['go']['main']['App']['SFTPMkdir'](arg1, arg2);
}

export function SFTPRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPRename'](arg1, arg2, arg3);
}

export function SFTPUpload(arg1, arg2) {
  return window['go']['main']['App']['SFTPUpload'](arg1, arg2);
}

export function SFTPUploadDir(arg1, arg2) {
  return window['go']['main']['App']['SFTPUploadDir'](arg1, arg2);
}

export function SFTPUploadDirDropped(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPUploadDirDropped'](arg1, arg2, arg3);
}

export function SFTPUploadDropped(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPUploadDropped'](arg1, arg2, arg3);
}

export function SaveExpectRule(arg1) {
  return window['go']['main']['App']['SaveExpectRule'](arg1);
}

export function SaveMacro(arg1) {
  return window['go']['main']['App']['SaveMacro'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function SaveSessionGroup(arg1) {
  return window['go']['main']['App']['SaveSessionGroup'](arg1);
}

export function SaveTerminalLog(arg1) {
  return window['go']['main']['App']['SaveTerminalLog'](arg1);
}

export function SaveTunnelConfig(arg1) {
  return window['go']['main']['App']['SaveTunnelConfig'](arg1);
}

export function SearchKnowledgeBase(arg1) {
  return window['go']['main']['App']['SearchKnowledgeBase'](arg1);
}

export function SelectPrivateKeyFile() {
  return window['go']['main']['App']['SelectPrivateKeyFile']();
}

export function StartSSHTunnel(arg1) {
  return window['go']['main']['App']['StartSSHTunnel'](arg1);
}

export function StartTFTPServer(arg1, arg2) {
  return window['go']['main']['App']['StartTFTPServer'](arg1, arg2);
}

export function StopSSHTunnel(arg1) {
  return window['go']['main']['App']['StopSSHTunnel'](arg1);
}

export function StopTFTPServer() {
  return window['go']['main']['App']['StopTFTPServer']();
}

export function SyncTerminalPath(arg1, arg2) {
  return window['go']['main']['App']['SyncTerminalPath'](arg1, arg2);
}

export function TFTPClientDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['TFTPClientDownload'](arg1, arg2, arg3);
}

export function TFTPClientUpload(arg1, arg2, arg3) {
  return window['go']['main']['App']['TFTPClientUpload'](arg1, arg2, arg3);
}

export function UpdateKnowledgeEntry(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateKnowledgeEntry'](arg1, arg2, arg3, arg4, arg5);
}

export function WriteMultipleTerminals(arg1, arg2) {
  return window['go']['main']['App']['WriteMultipleTerminals'](arg1, arg2);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}

export function WriteTerminalSequence(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteTerminalSequence'](arg1, arg2, arg3);
}
